# Generated by Django 4.0.2 on 2022-03-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_carfueltype_cartransmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images', verbose_name='ფოტო')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.CharField(choices=[], max_length=1, verbose_name='გამოშვების წელი')),
                ('steering_wheel_location', models.CharField(choices=[('1', 'მარჯვენა'), ('2', 'მარცხენა')], max_length=1, verbose_name='საჭის მდებარეობა')),
                ('engine_capacity', models.FloatField(verbose_name='ძრავის მოცულობა')),
                ('mileage', models.FloatField(verbose_name='გარბენი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('price', models.FloatField(verbose_name='ფასი')),
                ('author_fullname', models.CharField(max_length=255, verbose_name='ავტორის სრული სახელი')),
                ('author_phone_number', models.CharField(max_length=9, verbose_name='ტელეფონის ნომერი')),
                ('car_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carcolor', verbose_name='ფერი')),
                ('car_fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carfueltype', verbose_name='საწვავის ტიპი')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carmodel', verbose_name='მოდელი')),
                ('car_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cartransmission', verbose_name='გადამცემთა კოლოფი')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.carmanufacturer', verbose_name='მწარმოებელი')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carphoto', verbose_name='ფოტო')),
            ],
        ),
    ]
