# Generated by Django 4.0.2 on 2022-02-24 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=90, verbose_name='დეპარტამენტის სახელი')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=25, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='მეილი')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='შეიყვანეთ მხოლოდ 9 ციფრი', regex='\\d')], verbose_name='ტელეფონის ნომერი')),
                ('id_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='შეიყვანეთ 11 ციფრი', regex='\\d')], verbose_name='პირადი ნომერი')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='დეპარტამენტი')),
            ],
        ),
    ]
