# Generated by Django 4.0.2 on 2022-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_employee_options_remove_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='საწვავის ტიპი')),
            ],
            options={
                'verbose_name': 'საწვავის ტიპი',
            },
        ),
        migrations.CreateModel(
            name='CarTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='გადამცემთა კოლოფი')),
            ],
            options={
                'verbose_name': 'გადამცემთა კოლოფი',
            },
        ),
    ]
